/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DiseaseControlPanel;

import javax.swing.*;
import Business.*;
import Business.Admin.*;
import Business.DB4OUtil.*;
import Business.Disease.*;
import Business.Doctor.*;
import Business.Enterprise.*;
import Business.Network.*;
import Business.Patient.*;
import Business.Recode.*;
import java.awt.*;
import java.io.File;
/**
 *
 * @author prospace
 */
public class CenterLoginPanel extends javax.swing.JPanel {

    JPanel rightPanel;
    DiseaseCenter disease_center;
    /**
     * Creates new form CenterLoginPanel
     */
    File directory = new File("");
    String pex=directory.getAbsolutePath()+"/images/";
    public CenterLoginPanel(JPanel rightPanel, DiseaseCenter disease_center) {
        initComponents();
        this.rightPanel = rightPanel;
        this.disease_center = disease_center;
        init_work();
        //UI
        ImageIcon icon=new ImageIcon(pex+"logintitle1.png");
        logintitle.setText("");
        logintitle.setIcon(icon);
        ImageIcon icon1=new ImageIcon(pex+"id.png");
        namelable.setText("");
        namelable.setIcon(icon1);
        namelable1.setText("");
        namelable1.setIcon(icon1);
        ImageIcon icon2=new ImageIcon(pex+"password.png");
        passwdlable.setText("");
        passwdlable.setIcon(icon2);
        passwdlable1.setText("");
        passwdlable1.setIcon(icon2);
        initBTN();

    }
    //
    public void initBTN(){
        resetButton(LoginButton,
                pex+"login1.png",
                pex+"login2.png");
        resetButton(SignUpBtn,
                pex+"signup1.png",
                pex+"signup2.png");
    }
    
     public void resetButton(JButton btn,String path1,String path2){
       ImageIcon img1 = new ImageIcon(path1);
       ImageIcon img2 = new ImageIcon(path2);
      // ImageIcon img3 = new ImageIcon("/Users/cestdrama/Desktop/swg1207/display_pressed.jpg");        
          btn.setText("");
          btn.setSize(img2.getIconWidth(),img2.getIconHeight());
          btn.setContentAreaFilled(false);
          //BTN1.setBorderPainted(false);
          btn.setIcon(img1);
          btn.setPressedIcon(img2); 
          btn.setRolloverIcon(img2);
          //btn.setBorderPainted(false);
    }

    public void init_work(){
        disease_center.getAdminList().getList().clear();
        disease_center.getHospitalList().getHospitalList().clear();
        disease_center.getDiseaseList().getList().clear();
        for (String s: Datastore.getInstance().getAdmins().keySet()){
            disease_center.getAdminList().add(Datastore.getInstance().getAdmins().get(s));
        }
        for (String s: Datastore.getInstance().getHospitals().keySet()){
            disease_center.getHospitalList().Add(Datastore.getInstance().getHospitals().get(s));
        }
        for (String s: Datastore.getInstance().getDiseases().keySet()){
            if (Datastore.getInstance().getDiseases().get(s).getIsreport() == 0) continue;
            disease_center.getDiseaseList().add(Datastore.getInstance().getDiseases().get(s));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LUNText = new javax.swing.JTextField();
        LUPText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        SignUpBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AUNText = new javax.swing.JTextField();
        AUPText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        namelable = new javax.swing.JLabel();
        passwdlable = new javax.swing.JLabel();
        passwdlable1 = new javax.swing.JLabel();
        logintitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namelable1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("OfficerID:");

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignUpBtn.setText("Sign Up");
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monaco", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText(">>>>>>>>>>>>>>>>>>>>>>>Authorized admin officer>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");

        jLabel7.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Password:");

        namelable.setText("jLabel8");

        passwdlable.setText("jLabel8");

        passwdlable1.setText("   jLabel8");

        logintitle.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("User Name:");

        jLabel10.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Password:");

        namelable1.setText("jLabel8");

        jLabel15.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwdlable, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(namelable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LUNText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(LUPText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(namelable1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(passwdlable1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AUNText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AUPText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(SignUpBtn)
                .addGap(74, 74, 74)
                .addComponent(LoginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(logintitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelable, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LUNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwdlable, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LUPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelable1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AUNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwdlable1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AUPText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpBtn)
                    .addComponent(LoginButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        String s1 = LUNText.getText();
        String s2 = LUPText.getText();
        if (s1.equals("")) {
            JOptionPane.showMessageDialog(null, "Username shouldn't be empty!");
            return;
        }
        if (s2.equals("")) {
            JOptionPane.showMessageDialog(null, "Passwords shouldn't be empty!");
            return;
        }
        for (Admin x : disease_center.getAdminList().getList()){
            if (x.getUsername().equals(s1)&&x.getPasswords().equals(s2)){
                MainCenterPanel DCPanel = new MainCenterPanel(rightPanel,disease_center);
                rightPanel.add("amPanel",DCPanel);
                CardLayout layout = (CardLayout)rightPanel.getLayout();
                layout.next(rightPanel);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Username or Passwords error!");
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        // TODO add your handling code here:
        String s1 = LUNText.getText();
        String s2 = LUPText.getText();
        String s3 = AUNText.getText();
        String s4 = AUPText.getText();
        if (s1.equals("")) {
            JOptionPane.showMessageDialog(null, "Username shouldn't be empty!");
            return;
        }
        if (s2.equals("")) {
            JOptionPane.showMessageDialog(null, "Passwords shouldn't be empty!");
            return;
        }
        if (s3.equals("")) {
            JOptionPane.showMessageDialog(null, "Username shouldn't be empty!");
            return;
        }
        if (s4.equals("")) {
            JOptionPane.showMessageDialog(null, "Passwords shouldn't be empty!");
            return;
        }
        boolean flag = false;
        for (Admin x : disease_center.getAdminList().getList()){
            if (x.getUsername().equals(s1)){
                JOptionPane.showMessageDialog(null, "Username is existed!");
                return;
            }
            if (x.getUsername().equals(s3)&&x.getPasswords().equals(s4)){
                flag = true;
            }
        }
        if (flag == false){
            JOptionPane.showMessageDialog(null, "Authorized Person Information error");
            return;
        }
        Admin tmp = new Admin(s1,s2);
        disease_center.getAdminList().getList().add(tmp);
        Datastore.getInstance().getAdmins().put(s1, tmp);
        JOptionPane.showMessageDialog(null, "Sign Up Successfully!");
        LUNText.setText("");
        LUPText.setText("");
        AUNText.setText("");
        AUPText.setText("");
    }//GEN-LAST:event_SignUpBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AUNText;
    private javax.swing.JTextField AUPText;
    private javax.swing.JTextField LUNText;
    private javax.swing.JTextField LUPText;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logintitle;
    private javax.swing.JLabel namelable;
    private javax.swing.JLabel namelable1;
    private javax.swing.JLabel passwdlable;
    private javax.swing.JLabel passwdlable1;
    // End of variables declaration//GEN-END:variables
}
