/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalPanel;

/**
 *
 * @author prospace
 */
import javax.swing.*;
import Business.*;
import Business.Admin.*;
import Business.DB4OUtil.*;
import Business.Disease.*;
import Business.Doctor.*;
import Business.Enterprise.*;
import Business.Network.*;
import Business.Patient.*;
import Business.Recode.*;
import java.awt.*;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class MainHospitalPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainHospitalPanel
     */
    JPanel rightPanel;
    DiseaseCenter disease_center;
   File directory = new File("");
    String pex=directory.getAbsolutePath()+"/images/";
    public MainHospitalPanel(JPanel rightPanel, DiseaseCenter disease_center) {
        initComponents();
        this.rightPanel = rightPanel;
        this.disease_center = disease_center;
        populate();
        //UI
        ImageIcon icon=new ImageIcon(pex+"logintitle1.png");
        logintitle.setText("");
        logintitle.setIcon(icon);
        ImageIcon icon1=new ImageIcon(pex+"id.png");
        namelabel.setText("");
        namelabel.setIcon(icon1);
        namelabel.setText("");
        namelabel.setIcon(icon1);
        ImageIcon icon2=new ImageIcon(pex+"password.png");
        psdlabel.setText("");
        psdlabel.setIcon(icon2);
        psdlabel.setText("");
        psdlabel.setIcon(icon2);
        initBTN();
    }
    
    //
     public void initBTN(){
         resetButton(LoginBtn,
                pex+"login1.png",
                pex+"login2.png");
          resetButton(SignUpBtn,
                pex+"signup1.png",
                pex+"signup2.png");
        
    }
    //
     public void resetButton(JButton btn,String path1,String path2){
       ImageIcon img1 = new ImageIcon(path1);
       ImageIcon img2 = new ImageIcon(path2);
      // ImageIcon img3 = new ImageIcon("/Users/cestdrama/Desktop/swg1207/display_pressed.jpg");        
          btn.setText("");
          btn.setSize(img2.getIconWidth(),img2.getIconHeight());
          btn.setContentAreaFilled(false);
          //BTN1.setBorderPainted(false);
          btn.setIcon(img1);
          btn.setPressedIcon(img2); 
          btn.setRolloverIcon(img2);
          //btn.setBorderPainted(false);
    }
    
    public void populate(){
        NameCbx.removeAllItems();
        for (String s: Datastore.getInstance().getHospitals().keySet()){
            NameCbx.addItem(Datastore.getInstance().getHospitals().get(s).getName());
        }
        DepartCbx.removeAllItems();
        DepartCbx.addItem("Lab");
        DepartCbx.addItem("Manage");
        DepartCbx.addItem("Record");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameCbx = new javax.swing.JComboBox();
        DepartCbx = new javax.swing.JComboBox();
        Username = new javax.swing.JTextField();
        PWText = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        SignUpBtn = new javax.swing.JButton();
        logintitle = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        psdlabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1059, 718));

        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        SignUpBtn.setText("Sign Up");
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });

        logintitle.setText("jLabel5");

        jLabel11.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 102));
        jLabel11.setText("Hospital name:");

        jLabel12.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 102));
        jLabel12.setText("Department:");

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText(">>>>>Please choose >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ");

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText(">>>>>Please login below >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");

        jLabel13.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 102));
        jLabel13.setText("User name:");

        jLabel14.setFont(new java.awt.Font("Monaco", 3, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 102));
        jLabel14.setText("Password:");

        namelabel.setText("jLabel1");

        psdlabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DepartCbx, 0, 310, Short.MAX_VALUE)
                            .addComponent(NameCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PWText, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(Username)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logintitle)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DepartCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psdlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        String s1 = Username.getText();
        String s2 = PWText.getText();
        if (s1.equals("")==true||s2.equals("")==true){
            JOptionPane.showMessageDialog(null, "Info Not Filled!");
            return;
        }
        String s3 = (String)NameCbx.getSelectedItem();
        String s4 = (String)DepartCbx.getSelectedItem();
        for (HospitalAdmin x: Datastore.getInstance().getHospitals().get(s3).getAdminList().getList()){
            System.out.println(x.getUsername()+ "  "+ x.getPasswords() + x.getDepartment());
            if (x.getUsername().equals(s1)&&x.getPasswords().equals(s2)&&x.getDepartment().equals(s4)){
                if (s4.equals("Lab")){
                    LabPartMainPanel LabPanel = new LabPartMainPanel(rightPanel,Datastore.getInstance().getHospitals().get(s3));
                    rightPanel.add("LabPanel",LabPanel);
                    CardLayout layout = (CardLayout)rightPanel.getLayout();
                    layout.next(rightPanel);
                    return;
                }
                if (s4.equals("Manage")){
                    ManagementPartMainPanel ManagePanel = new ManagementPartMainPanel(rightPanel,Datastore.getInstance().getHospitals().get(s3));
                    rightPanel.add("ManagePanel",ManagePanel);
                    CardLayout layout = (CardLayout)rightPanel.getLayout();
                    layout.next(rightPanel);
                    return;
                }
                if (s4.equals("Record")){
                    RecordPartMainPanel RecordPanel = new RecordPartMainPanel(rightPanel,Datastore.getInstance().getHospitals().get(s3));
                    rightPanel.add("RecordPanel",RecordPanel);
                    CardLayout layout = (CardLayout)rightPanel.getLayout();
                    layout.next(rightPanel);
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Login Failed!");
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        // TODO add your handling code here:
        String s1 = Username.getText();
        String s2 = PWText.getText();
        if (s1.equals("")==true||s2.equals("")==true){
            JOptionPane.showMessageDialog(null, "Info Not Filled!");
            return;
        }
        String s3 = (String)NameCbx.getSelectedItem();
        String s4 = (String)DepartCbx.getSelectedItem();
        for (HospitalAdmin x: Datastore.getInstance().getHospitals().get(s3).getAdminList().getList()){
            System.out.println(x.getUsername()+ "  "+ x.getPasswords() + x.getDepartment());
            if (x.getUsername().equals(s1)&&x.getPasswords().equals(s2)&&x.getDepartment().equals(s4)){
                if (s4.equals("Manage")){
                    MainHospitalSignUpPanel MainSignUpPanel = new MainHospitalSignUpPanel(rightPanel,Datastore.getInstance().getHospitals().get(s3));
                    rightPanel.add("MainSignUpPanel",MainSignUpPanel);
                    CardLayout layout = (CardLayout)rightPanel.getLayout();
                    layout.next(rightPanel);
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "No Authorization");
    }//GEN-LAST:event_SignUpBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DepartCbx;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JComboBox NameCbx;
    private javax.swing.JTextField PWText;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logintitle;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel psdlabel;
    // End of variables declaration//GEN-END:variables
}
